import Navbar from "./../components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import { Session } from "next-auth";
import AuthProvider from "./../components/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider session = {session}>
        <div className="max-w-3xl mx-auto p-4">
          <div className="mt-8">
            {children}
          </div>
        </div>
        </AuthProvider>
      </body>
    </html>
  );
}
